schema_version = "1.0.0"

id = "little_bakery"
version = "0.1.0"
name = "Little Bakery"
tagline = "Bake automation addon."
maintainer = "tomanov"
# Supported types: "add-on", "theme"
type = "add-on"

blender_version_min = "5.0.0"

license = [
  "SPDX:GPL-2.0-or-later",
]
